version: '3.8'

services:
  postgres:
    container_name: postgres_db
    image: postgres
    environment:
      POSTGRES_DB: wa_dev
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mysecretpassword}
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  cache:
    container_name: redis_cache
    image: redis:latest
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: >
      --requirepass mysecretpassword
