version: '3.8'

services:
  postgres:
    container_name: postgres_db
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mysecretpassword}
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
